title = "Model Hyperparameters"

# More parameters to be added later
[dataset]
batch_size = 64
seed = 42
image_width = 256
image_height = 256
validation_split = 0.2
test_split = 0.5

# More parameters to be added later
[model]
seed = 42
learning_rate = 0.01
num_epochs = 20